/*
 *
 * BSD 3-Clause License
 * 
 * Copyright 2020 NXP 
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * UAVCAN data structure definition.
 *
 * AUTOGENERATED, DO NOT EDIT.
 *
 * Source File:
 * /home/cis/drones/s32k-bms/software/rddrone-bms772/src/nxp_bms/BMS_v1/public_regulated_data_types/uavcan/pnp/32742.NodeIDAllocationData.1.0.uavcan
 *
 * Template:
 * StructureType.j2
 *
 * Generated at:  2020-11-06 07:34:38.546838 UTC
 * Is deprecated: no
 * Fixed port ID: 32742
 * Full name:     uavcan.pnp.NodeIDAllocationData
 * Version:       1.0
 *
 */

#ifndef UAVCAN_PNP_NODEIDALLOCATIONDATA
#define UAVCAN_PNP_NODEIDALLOCATIONDATA
#include <canard_dsdl.h>

#include <uavcan/node/ID_1_0.h>

#define UAVCAN_PNP_NODE_IDALLOCATION_DATA_PORT_ID 32742

#define UAVCAN_PNP_NODE_IDALLOCATION_DATA_MSG_SIZE 9



typedef struct uavcan_pnp_node_idallocation_dataType
{
	uint64_t unique_id_hash;
    uint8_t allocated_node_id_size;
	uavcan_node_id allocated_node_id;
} uavcan_pnp_node_idallocation_data;

void uavcan_pnp_node_idallocation_data_serializeToBuffer(uavcan_pnp_node_idallocation_data* msg, uint8_t* const buffer, const size_t starting_bit)
{
	canardDSDLSetUxx(buffer, starting_bit + 0, msg->unique_id_hash, 48);
    canardDSDLSetUxx(buffer, starting_bit + 48, msg->allocated_node_id_size, 8);
    if(msg->allocated_node_id_size > 0)
    {
        uavcan_node_id_serializeToBuffer(&msg->allocated_node_id, buffer, starting_bit + 56);
    }
}

void uavcan_pnp_node_idallocation_data_deserializeFromBuffer(uavcan_pnp_node_idallocation_data* msg, const uint8_t* const buffer, const size_t buf_size, const size_t starting_bit)
{

	msg->unique_id_hash = canardDSDLGetU64(buffer, buf_size, starting_bit + 0, 48);
    msg->allocated_node_id_size = canardDSDLGetU8(buffer, buf_size, starting_bit + 48, 8);
    if(msg->allocated_node_id_size > 0)
    {
        uavcan_node_id_deserializeFromBuffer(&msg->allocated_node_id, buffer, buf_size, starting_bit + 56);
    }

    return msg;
}

#endif // UAVCAN_PNP_NODEIDALLOCATIONDATA
