/*
 *
 * BSD 3-Clause License
 * 
 * Copyright 2020 NXP 
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * UAVCAN data structure definition.
 *
 * AUTOGENERATED, DO NOT EDIT.
 *
 * Source File:
 * /home/cis/drones/s32k-bms/software/rddrone-bms772/src/nxp_bms/BMS_v1/public_regulated_data_types/uavcan/file/409.Write.1.0.uavcan
 *
 * Template:
 * ServiceType.j2
 *
 * Generated at:  2020-11-06 10:23:16.763840 UTC
 * Is deprecated: no
 * Fixed port ID: 409
 * Full name:     uavcan.file.Write
 * Version:       1.0
 *
 */

#ifndef UAVCAN_FILE_WRITE
#define UAVCAN_FILE_WRITE
#include <canard_dsdl.h>

#include <uavcan/file/Write/Request_1_0.h>
#include <uavcan/file/Write/Response_1_0.h>

#define UAVCAN_FILE_WRITE_PORT_ID 409

#define UAVCAN_FILE_WRITE_MSG_SIZE 313



typedef struct uavcan_file_writeType
{
	uavcan_file_write_request request;
	uavcan_file_write_response response;
} uavcan_file_write;

void uavcan_file_write_serializeToBuffer(uavcan_file_write* msg, uint8_t* const buffer, const size_t starting_bit)
{
    uavcan_file_write_request_serializeToBuffer(&msg->request, buffer, starting_bit + 0);
    uavcan_file_write_response_serializeToBuffer(&msg->response, buffer, starting_bit + 2488);
}

void uavcan_file_write_deserializeFromBuffer(uavcan_file_write* msg, const uint8_t* const buffer, const size_t buf_size, const size_t starting_bit)
{

        
        uavcan_file_write_request_deserializeFromBuffer(&msg->request, buffer, buf_size, starting_bit + 0);
        
        uavcan_file_write_response_deserializeFromBuffer(&msg->response, buffer, buf_size, starting_bit + 2488);

    return msg;
}

#endif // UAVCAN_FILE_WRITE
