/*
 *
 * BSD 3-Clause License
 * 
 * Copyright 2020 NXP 
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * UAVCAN data structure definition.
 *
 * AUTOGENERATED, DO NOT EDIT.
 *
 * Source File:
 * /home/cis/drones/s32k-bms/software/rddrone-bms772/src/nxp_bms/BMS_v1/public_regulated_data_types/regulated/zubax/sensor/wattmeter/DCSample.0.1.uavcan
 *
 * Template:
 * StructureType.j2
 *
 * Generated at:  2020-11-06 07:34:55.998085 UTC
 * Is deprecated: no
 * Fixed port ID: None
 * Full name:     regulated.zubax.sensor.wattmeter.DCSample
 * Version:       0.1
 *
 */

#ifndef REGULATED_ZUBAX_SENSOR_WATTMETER_DCSAMPLE
#define REGULATED_ZUBAX_SENSOR_WATTMETER_DCSAMPLE
#include <canard_dsdl.h>


#define REGULATED_ZUBAX_SENSOR_WATTMETER_DCSAMPLE_MSG_SIZE 8



typedef struct regulated_zubax_sensor_wattmeter_dcsampleType
{
	uavcan_si_unit_voltage_scalar voltage;
	uavcan_si_unit_electric_current_scalar current;
} regulated_zubax_sensor_wattmeter_dcsample;

void regulated_zubax_sensor_wattmeter_dcsample_serializeToBuffer(regulated_zubax_sensor_wattmeter_dcsample* msg, uint8_t* const buffer, const size_t starting_bit)
{
    uavcan_si_unit_voltage_scalar_serializeToBuffer(&msg->voltage, buffer, starting_bit + 0);
    uavcan_si_unit_electric_current_scalar_serializeToBuffer(&msg->current, buffer, starting_bit + 32);
}

void regulated_zubax_sensor_wattmeter_dcsample_deserializeFromBuffer(regulated_zubax_sensor_wattmeter_dcsample* msg, const uint8_t* const buffer, const size_t buf_size, const size_t starting_bit)
{

        
        uavcan_si_unit_voltage_scalar_deserializeFromBuffer(&msg->voltage, buffer, buf_size, starting_bit + 0);
        
        uavcan_si_unit_electric_current_scalar_deserializeFromBuffer(&msg->current, buffer, buf_size, starting_bit + 32);

    return msg;
}

#endif // REGULATED_ZUBAX_SENSOR_WATTMETER_DCSAMPLE
