/*
 *
 * BSD 3-Clause License
 * 
 * Copyright 2020 NXP 
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * UAVCAN data structure definition.
 *
 * AUTOGENERATED, DO NOT EDIT.
 *
 * Source File:
 * /home/cis/drones/s32k-bms/software/rddrone-bms772/src/nxp_bms/BMS_v1/public_regulated_data_types/uavcan/node/IOStatistics.0.1.uavcan
 *
 * Template:
 * StructureType.j2
 *
 * Generated at:  2020-11-06 07:34:52.635370 UTC
 * Is deprecated: no
 * Fixed port ID: None
 * Full name:     uavcan.node.IOStatistics
 * Version:       0.1
 *
 */

#ifndef UAVCAN_NODE_IOSTATISTICS
#define UAVCAN_NODE_IOSTATISTICS
#include <canard_dsdl.h>


#define UAVCAN_NODE_IOSTATISTICS_MSG_SIZE 15



typedef struct uavcan_node_iostatisticsType
{
	uint64_t num_emitted;
	uint64_t num_received;
	uint64_t num_errored;
} uavcan_node_iostatistics;

void uavcan_node_iostatistics_serializeToBuffer(uavcan_node_iostatistics* msg, uint8_t* const buffer, const size_t starting_bit)
{
	canardDSDLSetUxx(buffer, starting_bit + 0, msg->num_emitted, 40);
	canardDSDLSetUxx(buffer, starting_bit + 40, msg->num_received, 40);
	canardDSDLSetUxx(buffer, starting_bit + 80, msg->num_errored, 40);
}

void uavcan_node_iostatistics_deserializeFromBuffer(uavcan_node_iostatistics* msg, const uint8_t* const buffer, const size_t buf_size, const size_t starting_bit)
{

	msg->num_emitted = canardDSDLGetU64(buffer, buf_size, starting_bit + 0, 40);
	msg->num_received = canardDSDLGetU64(buffer, buf_size, starting_bit + 40, 40);
	msg->num_errored = canardDSDLGetU64(buffer, buf_size, starting_bit + 80, 40);

    return msg;
}

#endif // UAVCAN_NODE_IOSTATISTICS
