/*
 *
 * BSD 3-Clause License
 * 
 * Copyright 2020 NXP 
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * UAVCAN data structure definition.
 *
 * AUTOGENERATED, DO NOT EDIT.
 *
 * Source File:
 * /home/cis/drones/s32k-bms/software/rddrone-bms772/src/nxp_bms/BMS_v1/public_regulated_data_types/uavcan/pnp/cluster/32740.Discovery.1.0.uavcan
 *
 * Template:
 * StructureType.j2
 *
 * Generated at:  2020-11-06 10:23:10.237807 UTC
 * Is deprecated: no
 * Fixed port ID: 32740
 * Full name:     uavcan.pnp.cluster.Discovery
 * Version:       1.0
 *
 */

#ifndef UAVCAN_PNP_CLUSTER_DISCOVERY
#define UAVCAN_PNP_CLUSTER_DISCOVERY
#include <canard_dsdl.h>

#include <uavcan/node/ID_1_0.h>

#define UAVCAN_PNP_CLUSTER_DISCOVERY_PORT_ID 32740

#define UAVCAN_PNP_CLUSTER_DISCOVERY_MSG_SIZE 12

#define BROADCASTING_PERIOD 0x1
#define MAX_CLUSTER_SIZE 0x5


typedef struct uavcan_pnp_cluster_discoveryType
{
	uint8_t configured_cluster_size;
	uavcan_node_id_1_0_ known_nodes;
} uavcan_pnp_cluster_discovery;

void uavcan_pnp_cluster_discovery_serializeToBuffer(uavcan_pnp_cluster_discovery* msg, uint8_t* const buffer, const size_t starting_bit)
{
	canardDSDLSetUxx(buffer, starting_bit + 0, msg->configured_cluster_size, 3);
    uavcan_node_id_1_0__serializeToBuffer(&msg->known_nodes, buffer, starting_bit + 8);
}

void uavcan_pnp_cluster_discovery_deserializeFromBuffer(uavcan_pnp_cluster_discovery* msg, const uint8_t* const buffer, const size_t buf_size, const size_t starting_bit)
{

	msg->configured_cluster_size = canardDSDLGetU8(buffer, buf_size, starting_bit + 0, 3);
        
        uavcan_node_id_1_0__deserializeFromBuffer(&msg->known_nodes, buffer, buf_size, starting_bit + 8);

    return msg;
}

#endif // UAVCAN_PNP_CLUSTER_DISCOVERY
