/*
 *
 * BSD 3-Clause License
 * 
 * Copyright (c) 2020, NXP Drone and Rover Team
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * UAVCAN data structure definition.
 *
 * AUTOGENERATED, DO NOT EDIT.
 *
 * Source File:
 * /home/cis/drones/s32k-bms/software/rddrone-bms772/src/nxp_bms/BMS_v1/public_regulated_data_types/regulated/drone/sensor/BatteryChemistry.1.0.uavcan
 *
 * Template:
 * StructureType.j2
 *
 * Generated at:  2020-11-02 13:23:15.846537 UTC
 * Is deprecated: no
 * Fixed port ID: None
 * Full name:     regulated.drone.sensor.BatteryChemistry
 * Version:       1.0
 *
 */

#ifndef REGULATED_DRONE_SENSOR_BATTERYCHEMISTRY
#define REGULATED_DRONE_SENSOR_BATTERYCHEMISTRY
#include <canard_dsdl.h>


#define REGULATED_DRONE_SENSOR_BATTERY_CHEMISTRY_MSG_SIZE 0

#define CHEMISTRY_UNKNOWN 0x0
#define CHEMISTRY_LIPO 0x1
#define CHEMISTRY_LI_ION 0x2
#define CHEMISTRY_NICD 0x3
#define CHEMISTRY_NIMH 0x4
#define CHEMISTRY_LEAD_ACID 0x5


typedef struct regulated_drone_sensor_battery_chemistryType
{
	uint8_t chemistry;
} regulated_drone_sensor_battery_chemistry;

void regulated_drone_sensor_battery_chemistry_serializeToBuffer(regulated_drone_sensor_battery_chemistry* msg, uint8_t* const buffer, const size_t starting_bit)
{
	canardDSDLSetUxx(buffer, starting_bit + 0, msg->chemistry, 3);
}

void regulated_drone_sensor_battery_chemistry_deserializeFromBuffer(regulated_drone_sensor_battery_chemistry* msg, const uint8_t* const buffer, const size_t buf_size, const size_t starting_bit)
{

	msg->chemistry = canardDSDLGetU8(buffer, buf_size, starting_bit + 0, 3);

    return msg;
}

#endif // REGULATED_DRONE_SENSOR_BATTERYCHEMISTRY
