/*
 *
 * BSD 3-Clause License
 * 
 * Copyright (c) 2020, NXP Drone and Rover Team
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * UAVCAN data structure definition.
 *
 * AUTOGENERATED, DO NOT EDIT.
 *
 * Source File:
 * /home/cis/drones/s32k-bms/software/rddrone-bms772/src/nxp_bms/BMS_v1/public_regulated_data_types/regulated/zubax/sensor/bms/Technology.0.1.uavcan
 *
 * Template:
 * StructureType.j2
 *
 * Generated at:  2020-11-02 13:23:15.373510 UTC
 * Is deprecated: no
 * Fixed port ID: None
 * Full name:     regulated.zubax.sensor.bms.Technology
 * Version:       0.1
 *
 */

#ifndef REGULATED_ZUBAX_SENSOR_BMS_TECHNOLOGY
#define REGULATED_ZUBAX_SENSOR_BMS_TECHNOLOGY
#include <canard_dsdl.h>


#define REGULATED_ZUBAX_SENSOR_BMS_TECHNOLOGY_MSG_SIZE 1

#define UNKNOWN 0x0
#define OTHER 0x1
#define LI_CO_O2 0x16
#define LI_FE_PO4 0x17
#define LI_CO_O2_POUCH 0x18
#define LI_FE_PO4_POUCH 0x19
#define LI_ION_OTHER 0x31
#define NI_MH 0x32
#define NI_CD 0x33
#define NI_ZN 0x34
#define PB_AC 0x48
#define PB_AC_SEALED 0x49


typedef struct regulated_zubax_sensor_bms_technologyType
{
	uint8_t value;
} regulated_zubax_sensor_bms_technology;

void regulated_zubax_sensor_bms_technology_serializeToBuffer(regulated_zubax_sensor_bms_technology* msg, uint8_t* const buffer, const size_t starting_bit)
{
	canardDSDLSetUxx(buffer, starting_bit + 0, msg->value, 7);
}

void regulated_zubax_sensor_bms_technology_deserializeFromBuffer(regulated_zubax_sensor_bms_technology* msg, const uint8_t* const buffer, const size_t buf_size, const size_t starting_bit)
{

	msg->value = canardDSDLGetU8(buffer, buf_size, starting_bit + 0, 7);

    return msg;
}

#endif // REGULATED_ZUBAX_SENSOR_BMS_TECHNOLOGY
